/* A mining key, and the address the chain will pay it.
 *
 * Deliberately small. The pre-migration wallet derived addresses through `transaction.js`, which
 * carries RLP, gas maths and a signer — 441 lines this page has no use for. Mining needs exactly
 * three things: make a key, know its uncompressed public form (the template endpoint takes it as
 * bare hex), and know the address the coinbase credits.
 *
 * ── THE KEY NEVER LEAVES THIS TAB ────────────────────────────────────────────────────────────────
 *
 * It is generated by `crypto.getRandomValues`, held in memory, and used only to sign a proof after
 * a nonce has already won. It is not sent to CloudsForge, not written to a cookie, and not stored
 * unless the reader explicitly saves it. `docs/mining.md` is explicit that the private key is used
 * AFTER the hash loop, never inside it, and that only the public key is bound into the seed.
 */
import * as secp from './secp256k1.js'
import { keccak256 } from './keccak.js'

const hex = (bytes) => Array.from(bytes, (b) => b.toString(16).padStart(2, '0')).join('')

/**
 * EIP-55 mixed-case checksum. An address a reader can compare by eye against a block explorer is
 * worth the twenty lines; an all-lowercase one silently accepts a typo in a place that costs the
 * whole reward.
 */
export function toChecksumAddress(addr) {
  const body = addr.replace(/^0x/, '').toLowerCase()
  const digest = hex(keccak256(new TextEncoder().encode(body)))
  let out = '0x'
  for (let i = 0; i < body.length; i += 1) {
    out += parseInt(digest[i], 16) >= 8 ? body[i].toUpperCase() : body[i]
  }
  return out
}

/** The 65-byte uncompressed public key, as the template endpoint wants it: bare hex, no 0x. */
export function publicKeyHex(priv) {
  return hex(secp.publicKeyFromPrivate(priv, false))
}

/** The address the block reward is credited to: keccak of the public key body, last 20 bytes. */
export function addressFor(priv) {
  const pub = secp.publicKeyFromPrivate(priv, false)
  const digest = keccak256(pub.subarray(1)) // drop the 0x04 prefix — a format tag, not key material
  return toChecksumAddress(hex(digest.subarray(-20)))
}

/** A fresh key from the platform CSPRNG. Rejected if it is outside the curve order. */
export function generateKey() {
  return finalise(secp.randomPrivateKey())
}

/** A key a reader pastes back in, so a machine can be pointed at an address it already owns. */
export function keyFromHex(text) {
  const clean = String(text).trim().replace(/^0x/, '')
  if (!/^[0-9a-fA-F]{64}$/.test(clean)) throw new Error('a private key is 64 hex characters')
  const priv = new Uint8Array(32)
  for (let i = 0; i < 32; i += 1) priv[i] = parseInt(clean.slice(i * 2, i * 2 + 2), 16)
  if (!secp.isValidPrivateKey(priv)) throw new Error('that key is outside the curve order')
  return finalise(priv)
}

function finalise(priv) {
  return { priv, pubHex: publicKeyHex(priv), address: addressFor(priv), privHex: hex(priv) }
}
